### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#120]
`block-info-standard` are not standard?

``` js
const CLASSES = {
    info: 'mb1 block-info-standard', // blue
    warning: 'mb1 block-info-standard-warning', // yellow / orange
    error: 'mb1 block-info-standard-error' // red
};
```

@nico3333fr just confirm it's OK also on your side and we can close this issue.

**Comment by nico3333fr** [comment]
I've added `block-info-standard-warning` which was missing.

Anyway, this is okay for me for this one. 👍 

If you need one with grey background, you may use `block-info/block-info-error/block-info-warning` cf https://design-system-beta.netlify.com/containers/
