### ISSUE TITLE
Header for pages

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#129]
For each of the following pages, in the Zeplin design the content of the pages seems to be inside a container with a header with the title of the page. This header is missing.

[Reference](https://github.com/ProtonMail/protonmail-settings/issues/34)

**Comment by nico3333fr** [comment]
This is related to sticky headers: https://github.com/ProtonMail/design-system/issues/72 (I tried to do without any JS, and it was a bad idea, but with JS, this will be easier)
