### ISSUE TITLE
.block-info-standard-success is missing

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#133]
We need an `Alert` component with the green line also.

It looks like that currently if we use `block-info-standard-success`:
![Capture d’écran 2019-05-22 à 09 15 03](https://user-images.githubusercontent.com/1345786/58154532-20ce0780-7c72-11e9-9413-dda7e96461a8.png)

**Comment by nico3333fr** [comment]
This was scheduled to a near future! https://github.com/ProtonMail/design-system/blob/master/_sass/pm-styles/_pm-containers.scss#L57 
![image](https://user-images.githubusercontent.com/2578321/58166201-985b6100-7c89-11e9-9fa7-31f216e78633.png)

🥇
