### ISSUE TITLE
Text color missing

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#140]
<img width="815" alt="Capture d’écran 2019-05-23 à 05 15 31" src="https://user-images.githubusercontent.com/1345786/58223435-e8820400-7d19-11e9-8f7e-8978d667d6e4.png">

The text color used for `domains used` is missing in the design-system.

**Comment by nico3333fr** [comment]
It seems this is a "classic" text with `opacity` set to `.5`. You can achieve it using `<span class="opacity-50">2/2 domains used</span>`

Do you need a dedicated helper or is it okay?

**Comment by EpokK** [comment]
Thanks Nico
