### ISSUE TITLE
Increase width on Tooltip

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#145]
The width for Tooltip is too tight:
![Capture d’écran 2019-05-24 à 10 40 38](https://user-images.githubusercontent.com/1345786/58314725-64f70e80-7e10-11e9-877a-4009e77b7ecd.png)

Please increase the width.

**Comment by nico3333fr** [comment]
Done by https://github.com/ProtonMail/design-system/commit/d54c811923e347d0981bb8277bf44d7b823e1e83
