### ISSUE TITLE
Document helpers widths w10, etc.

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/design-system#152]
## Feature description

DOCUMENTATION. ALWAYS. 

## Use cases

Reference for layout.

## Benefits (optional)

DOCUMENTATION. ALWAYS.

**Comment by dhoko** [comment]
![documentation](https://user-images.githubusercontent.com/713283/58793415-5968cc00-85f6-11e9-9db7-930b9426297c.jpg)

**Comment by nico3333fr** [comment]
Yes but => 
![parceque](https://user-images.githubusercontent.com/2578321/58808846-166d1f80-861b-11e9-97cb-56c18c741c55.gif)
