### ISSUE TITLE
Small toggle

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#181]
Add a CSS class to make toggle component smaller. Thus, it will be consistent with small button inserted in table.

![Capture d’écran 2019-08-05 à 09 01 31](https://user-images.githubusercontent.com/1345786/62445053-a2a4db80-b75f-11e9-82ad-cc54c98fead0.png)

**Comment by nico3333fr** [comment]
Done via https://github.com/ProtonMail/design-system/commit/4231d4353900a095d4409d3caa447bd6b48122f6
