### ISSUE TITLE
Add vpnbasic and vpnplus colors - documentation

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/design-system#198]
## Feature description

Document. Always. Don’t discuss.

**Comment by EpokK** [comment]
I don't understand why you created this issue. I did it in [my PR](https://github.com/ProtonMail/design-system/pull/197). And it was mention in the description:

> Add new CSS class to handle new colors.
> Documentation updated.

![Capture d’écran 2019-08-21 à 12 04 20](https://user-images.githubusercontent.com/1345786/63423097-dd6b6c80-c40b-11e9-89cc-100f2ce3283d.png)

**Comment by nico3333fr** [comment]
My mistake, I missed it when I had a quick look at it.
