### ISSUE TITLE
Notifications are shown below modal

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/design-system#201]
## Quick summary of bug

If you trigger a notification from a modal, the notification is going to be displayed one layer below the modal window, which makes it darker in color.

## Actual Behavior

Example:

![Znhe01UaOV](https://user-images.githubusercontent.com/44697797/63498343-fb95a300-c4c5-11e9-857c-63fb5fda1b8f.gif)

## Expected Behavior

Notification should be displayed on top of the view.

## Steps to Reproduce the Problem

  1. Open a modal
  2. Trigger a notification (I tried to import an unsupported vCard file)
  3. Notice the issue

**Comment by mmso** [comment]
This should probably be in react-components

**Comment by nico3333fr** [comment]
@mmso a `z-index` update for notifications in the Design System is not enough you think? (this was my plan)

**Comment by mmso** [comment]
@nico3333fr yeah ok I guess that works too :)

**Comment by nico3333fr** [comment]
Yes, this will also fix notification display with modal on tiny viewports. Imho, notifications should always be on the top of the `z-index` :D

**Comment by nico3333fr** [comment]
This should be fixed now, notification on the TOP OF THE WOOOOORLD. :tada: 

Done via https://github.com/ProtonMail/design-system/commit/8ae49122a288a52d8e171645afd0dc647437f6ff
