### ISSUE TITLE
Spacing for loading button

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#209]
![Capture d’écran 2019-08-29 à 10 04 40](https://user-images.githubusercontent.com/1345786/63922279-a9fc9380-ca44-11e9-915b-8b4c7630202a.png)
Can we add spacing around the loading icon please?

**Comment by nico3333fr** [comment]
Done via https://github.com/ProtonMail/design-system/commit/b5ccadb7fb9ed92a5c42fd46dc5fa81b87b015de
