### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#212]
<img width="750" alt="Capture d’écran 2019-08-29 à 21 24 32" src="https://user-images.githubusercontent.com/1345786/63970032-72710400-caa3-11e9-8810-a00ab41d8b0e.png">

Progress bar should use primary color.

**Comment by nico3333fr** [comment]
These styles should not be like this???

![image](https://user-images.githubusercontent.com/2578321/64030119-3c389080-cb46-11e9-89c3-9eee99af9cbf.png)


https://design-system-beta.netlify.com/settings/
