### ISSUE TITLE
Keep button color when disabled

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#223]
Disabled buttons looks all the same. They should keep their color. Try to disable a primary button, it looks gray instead of a dark blue.
![Capture d’écran 2019-09-16 à 15 17 41](https://user-images.githubusercontent.com/1345786/64961171-25f43980-d895-11e9-8bc7-53dc6df7e6f5.png)

Work with designers to find the appropriate color.

**Comment by nico3333fr** [comment]
Yes, reported a looooooooooong time ago :)
![image](https://user-images.githubusercontent.com/2578321/64974620-74153700-d8ad-11e9-8669-2d9c4ea9663a.png)

Will ask again.
