### ISSUE TITLE
Dark mode implementation

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/design-system#245]
This issue convers the implementation of dark mode across all the projects.

- [x] dark mode applied to Angular Mail app
- [x] dark mode applied to Mail settings app
- [x] dark mode applied to Contacts (including Settings) app
- [x] dark mode applied to Calendar(including settings) app
- [x] dark mode applied to Design system website

**Comment by nico3333fr** [comment]
Missing styles:

- [ ] CodeMirror (filter Sieve)
- [ ] Disabled buttons !!!!!! 😠 
- [ ] special images for layout selectors? (or inlined images)
