### ISSUE TITLE
Finalize payments landing page

### ISSUE THREAD

**Issue by N4M3Z** [ProtonMail/design-system#255]
In order to release the redesigned payments landing page, we need to address the following issues:

1. The page does not auto-close on Firefox, as it defaults to a settings that stops `                window.close()` from working. We also have to assume this is a standard that can possibly be adopted by other browsers like Brave. The solution is to show a button `Confirm transaction` which will close the window through user action is it fails to autoclose for any reason, which should cover all cases. The button should only be shown after the countdown hits 0 (add a fraction of a second delay).

2. Certain styles seems to have a missing definition like `--body-fontsize` and `--main-bg-color`, etc. Please add the missing definitions so the HTML/CSS leaves nothing to chance.

3. The color gradient seems to cause very visible striping effect on Firefox, can we finetune it?
![image](https://user-images.githubusercontent.com/2804910/71675153-78daf980-2d7d-11ea-95b8-2d09d901a575.png)

The latest code is available here: https://gitlab.protontech.ch/ProtonMail/Slim-API/blob/5544fd6a6fd00f84370e928163b743748457b796/apps/Payments/resources/secure/token-v4.html

**Comment by N4M3Z** [comment]
@nico3333fr What's the status on this? We were targeting tomorrow's API deploy.

**Comment by nico3333fr** [comment]
@N4M3Z : I jump on it now, sorry, was very busy with Calendar stuff.

**Comment by nico3333fr** [comment]
Done :)
