### ISSUE TITLE
WebClient and proton-mail repository descriptions appear to have incorrect link to protonmail

### ISSUE THREAD

**Issue by aTable** [ProtonMail/design-system#261]
## Quick summary of bug

I'm wanting to create the [Dracula theme](https://github.com/dracula/dracula-theme/) for protonmail and I noticed a discrepancy in the naming of design-system sass variables and the class names used on the production site. The design-system has the approach of `pm-button` whereas production uses `pm_button` note the `-` vs `_`. 

![image](https://user-images.githubusercontent.com/2154448/77394841-07df3700-6dec-11ea-93e4-94c95b67159c.png)

My conclusion is the deployed production site is running the angular app because the [react naming](https://github.com/ProtonMail/react-components/blob/master/components/button/Button.tsx#L31) has the hyphen but [angular naming](https://github.com/ProtonMail/WebClient/blob/public/src/templates/message/filterButton.tpl.html#L34) has the underscore. If that's the case, I suggest updating the repository descriptions because it threw me into a bit of a loop having the app deployed at `mail.protonmail.com` but the ProtonMail/proton-mail say it's the one deployed there when it's the ProtonMail/WebClient one.

![image](https://user-images.githubusercontent.com/2154448/77395752-fb5bde00-6ded-11ea-8a18-2b7ccbe4ad8e.png)

Also, when will production receive the update to use the latest design-system, react-components and proton-mail repositories?

**Comment by dhoko** [comment]
:wave: 

Indeed today what's available live -> mail.protonmail.com is the v3 with Angular, cf https://github.com/ProtonMail/WebClient
The v4 is still WIP and it's available in beta. I changed the description on website for proton-mail.

> Also, when will production receive the update to use the latest design-system, react-components and proton-mail repositories?

We are currently testing the new design system, which you can use on https://beta.protonmail.com. We still have other features and fixes to add, so when we are confident that everything is ready, we will be releasing it to production. The current plan is to do this during the course of the year, more information will be shared on our blog and social media accounts as we progress.

**Comment by aTable** [comment]
Awesome, looking forward to using the beta. I added a [build system so custom user themes are neatly available in a webpage](https://github.com/aTable/design-system/commit/df141b5bfe181067870d1fffb1a14b0b3a7c953f) that might be of inspiration for the project.
