### ISSUE TITLE
modals page only displays the top navigation bar

### ISSUE THREAD

**Issue by starkfire** [ProtonMail/design-system#263]
## Quick summary of bug

The [modals](https://design-system.protontech.ch/modals/) page shows only the top navigation bar. The other elements are not visible and they seem to be hidden under a blue background.

## Actual Behavior

Only the top navbar is being displayed.

## Expected Behavior

The page is supposed to show the sidebar and the content.

## Steps to Reproduce the Problem

  1. Visit the [page](https://design-system.protontech.ch/modals/), or;
  2. Run `bundle exec jekyll serve --livereload` and visit `http://127.0.0.1:4000/modals/`

## Relevant logs/informations and/or screenshots

Chrome Version: 87.0.4280.88
Firefox Version: 83.0

No console output on devtools or errors on Jekyll.

![image](https://user-images.githubusercontent.com/26057339/102124064-bea3ab80-3e82-11eb-943c-b3ad8fa95c30.png)

## Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by nico3333fr** [comment]
Good catch, thanks a lot, a fix will be deployed in a few minutes. 👍

**Comment by nico3333fr** [comment]
Confirmed fixed on https://design-system.protontech.ch/modals/.

Thanks again @starkfire :)
