### ISSUE TITLE
Refresh icon is missing

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#27]
<img width="41" alt="capture d ecran 2019-03-08 a 11 05 21" src="https://user-images.githubusercontent.com/1345786/54022132-167f8f80-4192-11e9-89f1-7a500d6213cf.png">

**Comment by dhoko** [comment]
Idem for draggable icon
![screenshot from 2019-03-08 11-07-29](https://user-images.githubusercontent.com/713283/54022277-652d2980-4192-11e9-8949-643c62501101.png)

**Comment by nico3333fr** [comment]
As icons are not definitive, I already prepared them with other icons, so you'll be able to use it and we'll update them after ^^
