### ISSUE TITLE
Change stroke width icons

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/design-system#34]
## Feature description

the stroke is often too thin, it would be great to be able to change it.

## Use cases

![screenshot from 2019-03-08 16-10-36](https://user-images.githubusercontent.com/713283/54038914-fa93e200-41c1-11e9-81fc-b169c70035f3.png)

## Benefits (optional)

More visible, better rendering

_I tried a few things, I can't change the width_ :cry:

**Comment by nico3333fr** [comment]
Documentation to come ;)
