### ISSUE TITLE
Remove "shape" before icon name

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/design-system#75]
Every icon name is prefixed with `shape-`, can we remove it if it's useless?

**Comment by nico3333fr** [comment]
Don't forget they are inserted at the end of the pages with SVG tag:

```
 <g id="shape-info">
    <path d="M8,1a7,7,0,1,0,7,7A7,7,0,0,0,8,1ZM8,14a6,6,0,1,1,6-6A6,6,0,0,1,8,14Z" /><polygon points="8.5 6 6.5 6 6.5 7 7.5 7 7.5 11 6.5 11 6.5 12 9.5 12 9.5 11 8.5 11 8.5 6" /><rect x="7.5" y="4" width="1" height="1" />
 </g>
```

I prefixed them by `shape-` to avoid collisions in `id`s with other potential `id`s (in the HTML structure, `label`, etc): for example `id="shape-inbox"`, `id="shape-attention"`, `id="shape-account"`, etc. if we remove the `shape-` I imagine that there might be collisions with other `id`s. :-\

**Comment by EpokK** [comment]
:+1:
