### ISSUE TITLE
pm-button overrides pm-button--link

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/design-system#97]
## Quick summary of bug

In `react-components` there's a component, `LinkButton`, that generates some HTML like
```
<button class="pm-button pm-button--link" ...>
```
It seems pm-button overrides some of the features of pm-button--link, and therefore the displayed button is not the expected one.

## Actual Behavior

![image](https://user-images.githubusercontent.com/33841139/56972557-7fb8c900-6b6b-11e9-88e9-93c0c72e4873.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/33841139/56972612-94955c80-6b6b-11e9-83ab-9cc9caca4743.png)

## Steps to Reproduce the Problem

  1. Go to https://design-system-beta.netlify.com/buttons/
  2. Modify the HTML for the link button through the browser dev tools
  3. When adding `pm-button` to the class of the link button, the button changes its display

## Relevant logs/informations and/or screenshots

Screenshots above. I am using Chromium Version 73.0.3683.86 (Official Build) Built on Ubuntu, but I guess this behavior should be pretty generic.

## Possible fixes

I initially posted this issue in the `protonmail-settings` repo because it could be fixed by changing the code for the `LinkButton` component. However @dhoko suggests to fix this through CSS (adding a `:not`  or moving the rules after the pm-button), therefore I'm posting in this repo.

**Comment by nico3333fr** [comment]
@econdepe yes, they were not intended to be used with `pm-button` class (more a button that take `.link` behaviour)... but you're right, the modifier class is ambigous. 

I commit a fix right now.
